### ISSUE TITLE
vars.ArmA2OAProfile stay empty

### ISSUE THREAD

**Issue by LunaCB** [ebaydayz/SQF-Compact-Editor-Ouput#1]
I done everything as statet in the readme and my vars.ArmA2OAProfile loocks so:

 raP       ±   version     ProfileVariables :   ±   items    slots     Item0 y    Item1 ?   Item2 õ  ±    name uida  data ¤   readOnly     ?    type ¿    value Ó   ?   type  ARRAY Ó    items     Item0 ð   ?    data    ?    type *   value iremovedmysteamidhere ?   type  STRING ?    name unitsarrayoutput  data v  readOnly     õ    type à   value 
Begin units output for file: mission.sqf
End units output for file: mission.sqf
 õ   type  STRING õ    name objectsarrayoutput  data .  readOnly     ±    type œ   value 
Begin objects output for file: mission.sqf
End objects output for file: mission.sqf
 ±   type  STRING ±   

Here you got a screenshot of the half file, cause it will look different in text here on git:
http://puu.sh/hkjZN/7c0f60cff7.png

**Comment by ebaydayz** [comment]
Woops, forgot a step in the readme. Added it now. I will make a thread on the Epoch forums for this.
